#ifndef SECURE_CIPHER_CONFIG_H
#define SECURE_CIPHER_CONFIG_H

#include <sodium.h>

#define SCIPHER_MAGIC "SCIPH"
#define SCIPHER_MAGIC_LEN 5

#define HEADER_VERSION_LEGACY 1
#define HEADER_VERSION_GENERICHASH 2
#define HEADER_VERSION_CURRENT 3

#define CHUNK_SIZE 4096
#define CHUNK_SIZE_LARGE (256 * 1024)
#define CHUNK_SIZE_HUGE (1024 * 1024)
#define FILE_IO_BUFFER_SIZE (1024 * 1024)
#define LARGE_FILE_THRESHOLD (8 * 1024 * 1024)
#define HUGE_FILE_THRESHOLD (512LL * 1024 * 1024)
#define KEY_FILENAME "passphrase"
#define KEYDIR_ENV "SECURE_CIPHER_KEYDIR"
#define PWHASH_ENV "SECURE_CIPHER_PWHASH"
#define THREADS_ENV "SECURE_CIPHER_THREADS"
#define VM_ALLOW_ENV "SECURE_CIPHER_ALLOW_VM"
#define VM_EXIT_CODE 86
#define DEFAULT_WORKER_THREADS 0
#define MAX_WORKER_THREADS 32
#define MAX_PASSPHRASE_LEN 4096
#define KEYGEN_RANDOM_BYTES 32
#define FILE_SALT_BYTES crypto_pwhash_SALTBYTES

#define KDF_LEGACY 0
#define KDF_ARGON2ID 1
#define KDF_GENERICHASH 2
#define KDF_MACHINE_BLOB 3

#define DOMAIN_SEPARATOR "SCIPHER/XChaCha20-Poly1305/file-key/v1"
#define RECOVERY_FILENAME "RECOVERY_INSTRUCTIONS.txt"

#endif
